# ConfigTranslator - Wrangler Configuration
# This file configures Cloudflare Workers/Pages deployment

name = "configtranslator"
compatibility_date = "2024-01-01"

# D1 Database binding for translation counter and analytics
[[d1_databases]]
binding = "DB"
database_name = "configtranslator-db"
database_id = "3ed4ae1d-8bbc-45bd-a0ba-89374f7399fc"

# KV Namespace binding for rate limiting
[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "1d4d5e34ffad418ba5c26888b3c2def9"

# Environment variables
[vars]
NODE_ENV = "production"
NEXT_PUBLIC_SITE_NAME = "ConfigTranslator"
NEXT_PUBLIC_SITE_URL = "https://configtranslator.pages.dev"

# Secrets (set via wrangler secret put)
# OPENROUTER_API_KEY = "your_api_key_here"
# IP_HASH_SALT = "your_secure_salt_here" 